### PR TITLE
zipBy and mergeBy should remove duplicates

### LINKED ISSUE #598: zipBy and mergeBy should remove duplicates
**Describe the bug**
zipBy and mergeBy collect all possible keys but because the arrays from multiple languages are very similar, there are almost guaranteed to be duplicates. They should be removed.

### PR DESCRIPTION
**Pull request by JoveToo**
closes #598

### CODE REVIEW

**Comment by JoveToo** [comment]
Oops,. wrong branch

**Comment by elyukai** [comment]
On the last PR I could change the base branch. Is this bound to a certain condition? You just need to edit the PR title and then the base will also be editable, at least that worked for me.

**Comment by JoveToo** [comment]
I looked but couldn't see a way to do it. Perhaps I missed it.

**Comment by elyukai** [comment]
grafik
At least that's how I did it.

**Comment by JoveToo** [comment]
Thanks!

**Pull request closed without merging**
