### PR TITLE
style: wiki css grow

### PR DESCRIPTION
**Pull request by reactormonk**
Mostly grows the right side now.

### CODE REVIEW

**Review by elyukai — CHANGES_REQUESTED** [review]
To not impact readability due to long lines I would suggest adding a `max-width` of `39em`, which keeps the maximum line length at around 80 characters. But in general this is a great enhancement, thank you! ❤️

**Comment by reactormonk** [comment]
I understand your concerns regarding readability. This change specifically aims at letting the user (in this case me) decide what's most comfortable to read, without changing the defaults (which is ~ 80 characters) via `flex-basis`.

**Comment by elyukai** [comment]
But you can't really decide since it's determined by the width of the window only, which depends on the resolution of your screen (unless you fine-tune the width). And since people will probably have different opinions on how wide the text should be, but also have different monitors, they shouldnt be required to resize the window to resize the text length, especially if they want to have it smaller or even larger than what their current screen provides. So there is some size to be defined, and while it can be responsive in general, we need a maximum size so that the text doesn't get in the way for people who don't want to have it that large.

So, yeah, while I understand that wider texts might be preferable by some it should not reduce readability for others and in that case I go with the researched maximum line length of 80 characters, which is `39em` in this specific case and which is still 50% wider than the current view.

Btw, the `flex-basis` for the `aside` should be `34em` maximum, otherwise some liturgical chant titles will get cut. (*Herbeirufung der Heerscharen des Rattenkindes (Vampirfledermäuse)* is quite long … 🙃)

**Comment by elyukai** [comment]
Closing for housekeeping reasons, please reopen if work is continued.

**Pull request closed without merging**
