### PR TITLE
Enable devtools

### LINKED ISSUE #575: React devtools and displayName
Hey, I started looking at the code and realized that it’s not super easy to debug the React hierarchy. Adding devtools is pretty easy by adding this (or a more cross-platform version of it) to `main.ts`:

```js
BrowserWindow.addDevToolsExtension (path.join (
  os.homedir (),
  ".config/chromium/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.0.6_0/",
))
```

But the resulting devtools view shows all React components as “Anonymous”.

I guess that’s because we use a lot of anonymous functions as components, and neither tsc nor the React devtools infer names for them like the Firefox or Chromium debuggers do.

Does anyone know how to improve this? AFAIK tsc doesn’t have compiler plugins that we could use, and I think it would be overkill to use babel or so just to get this feature.

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #575, supersedes #578. Retained changes:

- Added some code to load and connect the devtools (`electron-devtools-installer` makes them available and `redux-devtools-extension` connects it to the store). This alone would go most of the way, except for components still appearing as `Anonymous`.
- Switched to `esm` to load modules using `import` syntax instead of compiling to CommonJS modules. Once Electron runs Node 14, we can just get rid of the shims (`index.js` and `esmPreload.js`). An alternative here would be to configure Babel to compile things to CommonJS modules as tsc did.

### CODE REVIEW

**Comment by flying-sheep** [comment]
Hmm, there’s still failures that don’t occur locally and don’t seem to be from my code

**Comment by flying-sheep** [comment]
Awesome! I think this should help everyone to debug the UI. What was your current process for that? just breakpoints? And how did you debug the redux store?

**Comment by elyukai** [comment]
I used the functions in `Debug/Trace` to log them since they use `Data/Show` to display the custom data structures which makes it way easier to understand. Thats why I use it for everything – it's not too bad if you watch the TS files. 😅🙈

**Comment by flying-sheep** [comment]
ah, looks good. IDK if the Redux devtool can be configured to use something custom to display data structures, but it’s a great help in any case I think.

**Pull request merged**
