### PR TITLE
Show individually enabled professions as common

### LINKED ISSUE #509: SA Tradition (Geoden): Effects

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #509

At least I think it does, https://github.com/elyukai/optolith-client/issues/509#issuecomment-624717977 mentions other changes, but I don’t know what’s missing

### CODE REVIEW

**Comment by flying-sheep** [comment]
hi, the failures are the same as in my other PR and seem to be upstream. Can I do anything to help this along?

**Comment by elyukai** [comment]
It might be failing because I think secrets are not provided for pull requests from outside. So I think I'm just gonna merge it. 😅🙈

**Comment by elyukai** [comment]
It works in `develop` branch... 😅🙈

**Comment by flying-sheep** [comment]
cool!

**Comment by elyukai** [comment]
Well *I* have to thank you for your contribution!!!!!! ❤

**Comment by flying-sheep** [comment]
haha well this is probably the smallest patch I’ve ever done

**Comment by elyukai** [comment]
Even small changes can make a big difference! 🤗

**Pull request merged**
